version: '3'

services:
  base:
    image: ghcr.io/craigcarey/dotfiles/base
    container_name: base
    entrypoint: "/usr/sbin/sshd -D"
    working_dir: /home/craig/
    hostname: docker-base
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /home/craig/:/home/craig/
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    networks:
      static-network:
        ipv4_address: 172.20.128.1

#   gst:
#     image: gst
#     container_name: gst
#     entrypoint: "/usr/sbin/sshd -D"
#     working_dir: /home/craig/
#     hostname: docker-gst
#     volumes:
#       - /tmp/.X11-unix:/tmp/.X11-unix
#       - /home/craig/:/home/craig/
#     security_opt:
#       - seccomp:unconfined
#       - apparmor:unconfined
#     networks:
#       static-network:
#         ipv4_address: 172.20.128.2

networks:
  static-network:
    ipam:
      config:
        - subnet: 172.20.0.0/16
