version: '3'

services:
  db:
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - ./nextcloud/mariadb:/var/lib/mysql
    env_file:
      - db.env

  nextcloud:
    image: nextcloud:apache
    restart: always
    volumes:
      - /media/4tb/nextcloud/app:/var/www/html
    environment:
      - VIRTUAL_HOST=nextcloud.cynitec.uk
      - LETSENCRYPT_HOST=nextcloud.cynitec.uk
      - LETSENCRYPT_EMAIL=cynitec@gmail.com
      - MYSQL_HOST=db
    env_file:
      - db.env
    depends_on:
      - db
    networks:
      - proxy-tier
      - default

  nginx:
    image: nginx:1.15-alpine
    restart: always
    volumes:
      - ./website/:/usr/share/nginx/html
    environment:
      - VIRTUAL_HOST=cynitec.uk
      - LETSENCRYPT_HOST=cynitec.uk
      - LETSENCRYPT_EMAIL=cynitec@gmail.com
    networks:
      - proxy-tier
      - default

  proxy:
    build: ./proxy
    restart: always
    ports:
      - 80:80
      - 443:443
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    volumes:
      - ./nextcloud/certs:/etc/nginx/certs:ro
      - ./nextcloud/vhost.d:/etc/nginx/vhost.d
      - ./nextcloud/html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - proxy-tier

  letsencrypt-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    volumes:
      - ./nextcloud/certs:/etc/nginx/certs
      - ./nextcloud/vhost.d:/etc/nginx/vhost.d
      - ./nextcloud/html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - proxy-tier
    depends_on:
      - proxy

  emby:
    image: linuxserver/emby
    restart: always
    container_name: emby
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - UMASK_SET=022 #optional
    volumes:
      - ./emby/config:/config
      - ~/4tb/media/tv:/data/tv
      - ~/4tb/media/films:/data/movies
      - ~/4tb/media/education:/data/education
      - /opt/vc/lib:/opt/vc/lib #optional
    ports:
      - 8096:8096
      - 8920:8920 #optional

volumes:
  db:
  nextcloud:
  certs:
  vhost.d:
  html:

networks:
  proxy-tier:
